#!/usr/bin/env python

import os
import sys
import subprocess

# Custom build configuration for Godot with C#, Python, and Uiverse.io integration

# Initialize the environment
env = Environment()

# Add custom modules
custom_modules = [
    'modules/mono',           # C# support
    'modules/python',         # Python integration
    'modules/uiverse',        # Uiverse.io integration
]

# Configure build options
opts = Variables([], ARGUMENTS)
opts.Add(BoolVariable('use_mono', 'Enable Mono (C#) support', True))
opts.Add(BoolVariable('use_python', 'Enable Python support', True))
opts.Add(BoolVariable('use_uiverse', 'Enable Uiverse.io integration', True))
opts.Add(EnumVariable('target', 'Compilation target', 'debug', ['debug', 'release_debug', 'release']))
opts.Add(EnumVariable('platform', 'Target platform', '', ['', 'windows', 'linux', 'osx']))
opts.Add(EnumVariable('bits', 'Target architecture', '64', ['32', '64']))

# Update the environment with the options
opts.Update(env)

# Platform-specific configurations
if env['platform'] == 'windows':
    env.Append(CCFLAGS=['/EHsc', '/bigobj'])
    if env['target'] == 'debug':
        env.Append(CCFLAGS=['/MDd', '/Od', '/EHsc', '/RTC1'])
    else:
        env.Append(CCFLAGS=['/MD', '/O2', '/EHsc'])
elif env['platform'] in ['linux', 'osx']:
    env.Append(CCFLAGS=['-fPIC', '-g3'])
    if env['target'] == 'debug':
        env.Append(CCFLAGS=['-O0'])
    else:
        env.Append(CCFLAGS=['-O3'])

# Configure Python integration
if env['use_python']:
    python_config = subprocess.check_output(['python3-config', '--includes']).decode().strip()
    env.Append(CCFLAGS=python_config.split())
    env.Append(LIBS=['python3'])

# Configure Mono/C# integration
if env['use_mono']:
    env.Append(CCFLAGS=['-DHAS_MONO'])
    if env['platform'] == 'windows':
        env.Append(LIBS=['mono-2.0-sgen'])
    else:
        env.Append(LIBS=['monosgen-2.0'])

# Configure Uiverse.io integration
if env['use_uiverse']:
    env.Append(CCFLAGS=['-DHAS_UIVERSE'])
    env.Append(CPPPATH=['#modules/uiverse/include'])

# Main build targets
SConscript('godot/SConstruct')

# Custom modules build
for module in custom_modules:
    if os.path.exists(module + '/SCsub'):
        SConscript(module + '/SCsub')

# Help text
Help("""
Custom Godot build with C#, Python, and Uiverse.io integration
Available targets:
    debug
    release_debug
    release
Available platforms:
    windows
    linux
    osx
""") 